In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [11]:
from sklearn.datasets import load_digits
digit = load_digits()

In [15]:
kf = KFold(n_splits=5)
kfs = StratifiedKFold(n_splits=5)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [17]:
def score_calc(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [19]:
lr=[]
svm=[]
rf=[]
for index1,index2 in kf.split(digit.data): #index1=train index, index2 = test index
    X_train, X_test, y_train, y_test = digit.data[index1] , digit.data[index2],\
                                       digit.target[index1], digit.target[index2]      
                                       
    lr.append(score_calc(LogisticRegression(),X_train, X_test, y_train, y_test)) 
    svm.append(score_calc(SVC(),X_train, X_test, y_train, y_test)) 
    rf.append(score_calc(RandomForestClassifier(),X_train, X_test, y_train, y_test)) 
                                                           

c:\Users\10726620\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\10726620\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.

In [20]:
lr

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [21]:
svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [22]:
rf

[0.9388888888888889,
 0.9305555555555556,
 0.958217270194986,
 0.9610027855153204,
 0.9303621169916435]

In [24]:
from sklearn.model_selection import cross_val_score

In [26]:
print(cross_val_score(LogisticRegression(),digit.data,digit.target))
print(lr)

[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.9277777777777778, 0.8666666666666667, 0.9387186629526463, 0.935933147632312, 0.9080779944289693]


c:\Users\10726620\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\10726620\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.

In [27]:
print(cross_val_score(SVC(),digit.data,digit.target))
print(svm)

[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.9694444444444444, 0.9472222222222222, 0.9832869080779945, 0.9888579387186629, 0.9415041782729805]


In [28]:
print(cross_val_score(RandomForestClassifier(),digit.data,digit.target))
print(rf)

[0.93333333 0.91111111 0.95264624 0.96935933 0.91922006]
[0.9388888888888889, 0.9305555555555556, 0.958217270194986, 0.9610027855153204, 0.9303621169916435]
